<a href="https://colab.research.google.com/github/phmouras/Projeto_Pos/blob/main/tst.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
from scipy import special

N = 5

col = np.cos(range(N))

T = np.zeros([N,N])

T[0,] = 1
T[1,] = col

for i in (range(2,N)):
  T[i,] = 2*col*T[i-1,] - T[i-2,]

f = np.arcsin(col)      ### Função para ajustar f = arcsin(eta)

Coef = np.dot( np.linalg.inv(T), f)

print (T)

np.linalg.inv(T)



[[ 1.          1.          1.          1.          1.        ]
 [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]
 [ 1.         -0.41614684 -0.65364362  0.96017029 -0.14550003]
 [ 1.         -0.9899925   0.96017029 -0.91113026  0.84385396]
 [ 1.         -0.65364362 -0.14550003  0.84385396 -0.95765948]]


array([[ 0.15805561,  0.32195104,  0.28432257,  0.17732142,  0.05834935],
       [ 0.32195104,  0.33232853, -0.1688679 , -0.32980935, -0.15560231],
       [ 0.28432257, -0.1688679 , -0.93255365,  0.13994567,  0.67715332],
       [ 0.17732142, -0.32980935,  0.13994567, -0.2001239 ,  0.21266616],
       [ 0.05834935, -0.15560231,  0.67715332,  0.21266616, -0.79256652]])